stable_coins = {
    "usdc",
    "usdt",
    "usdy",
    "tusd",
    "susd",
    "musd",
    "ausd",
    "fdusd",
    "coin",
    "scallop_usdc",
    "scallop_wormhole_usdt",
    "scallop_deep",
    "scallop_sca",
    "scallop_sui",
    "scallop_sb_eth",
}
